# Generated by Django 6.0 on 2025-12-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condidates',
            new_name='Candidates',
        ),
    ]
