# Generated by Django 6.0 on 2025-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_rename_condidates_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='age',
            field=models.IntegerField(),
        ),
    ]
