# Generated by Django 6.0 on 2025-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_alter_candidates_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('card_ID', models.IntegerField()),
            ],
        ),
    ]
