# Generated by Django 6.0 on 2025-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_voter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.AddField(
            model_name='candidates',
            name='party',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
