# Generated by Django 6.0 on 2025-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_delete_voter_candidates_party_alter_candidates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='party',
            field=models.CharField(max_length=200),
        ),
    ]
