# Generated by Django 6.0 on 2025-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0006_candidates_votes_alter_candidates_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
